# Generated by Django 4.1.1 on 2022-09-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('priority', models.CharField(choices=[('L', 'LOW'), ('M', 'MEDIUM'), ('H', 'HIGH')], max_length=1, verbose_name='Priority')),
                ('status', models.CharField(choices=[('I', 'IN PROGRESS'), ('P', 'PENDING'), ('C', 'COMPLETED')], max_length=1, verbose_name='Status')),
                ('category', models.ManyToManyField(to='tasks.category')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['id'],
            },
        ),
    ]
